from openai import OpenAI
import json

client = OpenAI()

# 1. Define a list of callable tools for the model
tools = [
    {
        "type": "function",
        "name":  "get_horoscope",
        "description": "Get today's horoscope for an astrological sign.",
        "parameters": {
            "type": "object",
            "properties": {
                "sign": {
                    "type": "string",
                    "description": "An astrological sign like Libra or Sagittarius",
                },
            },
            "required": ["sign"],
        },
    },
]


def get_horoscope(sign: str) -> str:
    return (
        f"{sign}: You enter the month in your usual buoyant mood, "
        "the part of you that others find so loveable."
    )


# Create a running input list we will add to over time
input_list = [{"role": "user", "content": "What is my horoscope? I am a Sagittarius."}]

# 2. Prompt the model with tools defined
response = client.responses.create(
    model="gpt-5",
    tools=tools,
    input=input_list,
)
print("Initial response JSON for the prompt with tools defined:")
print(response.to_json())

# Save function call outputs for subsequent requests
input_list += response.output

for item in response.output:
    if item.type == "function_call":
        if item.name == "get_horoscope":
            # 3. Execute the function logic for get_horoscope
            horoscope = get_horoscope(json.loads(item.arguments))

            # 4. Provide function call results to the model
            input_list.append(
                {
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": json.dumps({"horoscope": horoscope}),
                }
            )

print("\nFinal input debug log:")
print(input_list)

response = client.responses.create(
    model="gpt-5",
    instructions="Respond only with a horoscope generated by a tool.",
    tools=tools,
    input=input_list,
)

# 5. The model should be able to give a response!
print("\nFinal output debug log:")
print(response.to_json())
print(response.output_text)

print("\nFinal input:")
print(input_list[0]["content"])
print("\nFinal output:")
print(f"{response.output_text.rsplit(":", 1)[1].strip()}")
